### ISSUE TITLE
Path not found for MoneroWebWorker.js

### ISSUE THREAD

**Issue by dutu** [woodser/monero-ts#167]
When using `new MoneroConnectionManager()` the following error occurs:
```text
Error: Qualified path resolution failed: we looked for the following paths, but none could be accessed.

Source path: C:\Users\dutu\WebstormProjects\xwm\.yarn\unplugged\monero-ts-npm-0.9.5-b6e7d4fa73\node_modules\monero-ts\dist\dist\src\main\js\common\MoneroWebWorker.js
```

Variable `moneroTS.LibraryUtils.WORKER_DIST_PATH` is set to `file://C:\Users\dutu\WebstormProjects\xwm\.yarn\unplugged\monero-ts-npm-0.9.5-b6e7d4fa73\node_modules\monero-ts\dist\dist\src\main\js\common\MoneroWebWorker.js`.

When  `new MoneroConnectionManager(false)` the error is not seen.

I can see the file `MoneroWebWorker.js` is not found in the package in `monero-ts\dist\dist\src\main\js\common\` directory.

**Comment by dutu** [comment]
It looks wired.
I debugged the code you mentioned and I see `__dirname` is `C:\Users\dutu\WebstormProjects\monero-ts\dist\src\main\ts\common`, which seams to be correct.
`path.join(curPath, "../../../../dist/src/main/js/common")` gives `C:\Users\dutu\WebstormProjects\monero-ts\dist\dist\src\main\js\common`, and we have `dist\dist\src` in the path.

Secondly, I don't see any directory `dist/src/main/js/common` that you mentioned, but only `dist/src/main/ts/common`. 
(`MoneroWebWorker.js` is located here, not `js` directory as expected by `LibraryUtils`).


![Screenshot 2024-01-10 154924](https://github.com/monero-ecosystem/monero-ts/assets/6230798/9b114316-ceee-46a1-bd7c-3cce53a479cf)

**Comment by woodser** [comment]
Ah, this bug may be as simple as searching for "monero-ts/dist" within your path "...\monero-ts\dist\src\...", which isn't a hit due to the backslashes.

In that case, I'd expect this to always occur in non-web environment on Windows.

If it's easy for you to debug, mind changing this line to confirm a fix?

Current:
`if (curPath.indexOf("monero-ts/dist") === -1 && curPath.indexOf("monero-ts\\dist") === -1) curPath = path.join(curPath, "../../../../dist/src/main/js/common");`

After fix:
`if (curPath.indexOf("monero-ts/dist") === -1 && curPath.indexOf("monero-ts\\dist") === -1) curPath = path.join(curPath, "../../../../dist/src/main/js/common");`

**Comment by dutu** [comment]
I see, it makes sense. Your code modification works.

BTW, perhaps a suitable approach to make it OS agnostic would be:
```ts
let curPath = path.normalize(__dirname);
const targetPath = path.join('monero-ts', 'dist');
if (!curPath.includes(targetPath)) curPath = path.join(curPath, "../../../../dist/src/main/js/common");
```

I've tested it and it works ok.

**Comment by woodser** [comment]
Fixed in https://github.com/woodser/monero-ts/commit/5b87c09aa5122ba5861c1d3b90d0f305b65c6344. Thanks!
