### ISSUE TITLE
Failed to parse URL

### ISSUE THREAD

**Issue by starkbamse** [woodser/monero-ts#180]
Error [TypeError]: Failed to parse URL from /home/xxx/Documents/GitHub/xxx-router/node_modules/monero-ts/dist/dist/monero_wallet_keys.wasm
    at LibraryUtils.deserializeError (/home/xxx/Documents/GitHub/xxx-router/node_modules/monero-ts/dist/src/main/ts/common/LibraryUtils.js:253:106)
    at LibraryUtils.invokeWorker (/home/xxx/Documents/GitHub/xxx-router/node_modules/monero-ts/dist/src/main/ts/common/LibraryUtils.js:242:26)
    at async MoneroWalletKeysProxy.createWallet (/home/xxx/Documents/GitHub/xxx-router/node_modules/monero-ts/dist/src/main/ts/wallet/MoneroWalletKeys.js:381:5)
    at async MoneroWalletKeys.createWallet (/home/xxx/Documents/GitHub/xxx-router/node_modules/monero-ts/dist/src/main/ts/wallet/MoneroWalletKeys.js:63:25)
Worker error: TypeError: Failed to parse URL from /home/xxx/Documents/GitHub/xxx-router/node_modules/monero-ts/dist/dist/monero_wallet_keys.wasm
    at Object.fetch (node:internal/deps/undici/undici:11576:11)

```typescript
import moneroTs from "monero-ts";

    moneroTs.createWalletKeys({networkType: moneroTs.MoneroNetworkType.MAINNET, language: "English"}).then( async (result)=>{
      const address=await result.getAddress(0,0);
      const seed=await result.getSeed();
      console.log(seed)
      const duplicateWallet=await moneroTs.createWalletKeys({networkType:moneroTs.MoneroNetworkType.MAINNET,seed:seed});
      const address2=await result.getAddress(0,0);
      console.log(address)
      console.log(address2)
});
```

**Comment by woodser** [comment]
That code is working for me, suggesting something specific to your environment. You could try the previous release version (0.9.5) in case something was broken in the last release.

**Comment by starkbamse** [comment]
> That code is working for me, suggesting something specific to your environment. You could try the previous release version (0.9.5) in case something was broken in the last release.

What node version are you running?

**Comment by woodser** [comment]
Node v20.10.0
npm 10.2.5

**Comment by starkbamse** [comment]
I assume you are running windows?

**Comment by woodser** [comment]
MacOS

**Comment by woodser** [comment]
Are you running on Windows and/or Next.js?

**Comment by woodser** [comment]
Also, are you using a supported version of Node.js LTS?

> Node 20 LTS is recommended. Alternatively, Node 16 and 18 LTS work using the --experimental-wasm-threads flag.

**Comment by adhisimon** [comment]
I confirmed this bug happened on Node.js 18 and 20 but it can run on Node.js 16 without problem.

**Comment by woodser** [comment]
If anyone can provide a reliable test case or setup to reproduce, I can investigate more thoroughly. As it is, the only way I'm able to see this error is in Next.js as documented in [this issue](https://github.com/woodser/monero-ts/issues/181).

Otherwise I cannot reproduce in Node.js 20.

**Comment by VladimirDiamandi** [comment]
Hello. I'm having the same problem. If I use nodejs 16 everything works.

```
Error [TypeError]: Failed to parse URL from /test-api/node_modules/monero-ts/dist/dist/monero_wallet_full.wasm
    at LibraryUtils.deserializeError (/test-api/node_modules/monero-ts/dist/src/main/ts/common/LibraryUtils.js:253:106)
    at LibraryUtils.invokeWorker (/test-api/node_modules/monero-ts/dist/src/main/ts/common/LibraryUtils.js:242:26)
    at async MoneroWalletFullProxy.createWallet (/test-api/node_modules/monero-ts/dist/src/main/ts/wallet/MoneroWalletFull.js:1852:5)
    at async MoneroWalletFull.createWallet (/test-api/node_modules/monero-ts/dist/src/main/ts/wallet/MoneroWalletFull.js:173:25)
    at async Wallet.create (file://test-api/test.js:15:24)
    at async main (file://test-api/test.js:30:18)
Worker error: TypeError: Failed to parse URL from /test-api/node_modules/monero-ts/dist/dist/monero_wallet_full.wasm
    at node:internal/deps/undici/undici:12345:11
```

Code:
```
import { MoneroNetworkType, createWalletFull } from "monero-ts";

export class Wallet {
  static Network = MoneroNetworkType;

  moneroWalletFull;

  static async create({ server, ...options }) {
    const walletFull = await createWalletFull({
      language: "English",
      ...options,
      server,
    });

    return new Wallet(walletFull);
  }

  constructor(wallet) {
    this.moneroWalletFull = wallet;
  }
}

const main = async () => {
  const wallet = await Wallet.create({
    networkType: Wallet.Network.TESTNET,
    server: "http://125.229.105.12:28081",
  });

  console.log(wallet);
};

main();
```

Environment:
```
    Node.js v20.11.1
    OS: macOS Sonoma 14.3.1
```

package.json
```
{
  "name": "monero",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "type": "module",
  "scripts": {
    "test": "node ./index.js"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "monero-ts": "^0.9.6",
    "undici": "^6.6.2"
  },
  "volta": {
    "node": "20.11.1"
  }
}
```

**Comment by dutu** [comment]
Same issue 
```text
Failed to parse URL from .....node_modules/monero-ts/dist/dist/monero_wallet_keys.wasm
```

node v21.6.2 on debian

**Comment by dutu** [comment]
The error happens when executing
https://github.com/woodser/monero-ts/blob/14758245cf0ed8fd8586a4a42bdc89e35aa661a5/src/main/ts/common/LibraryUtils.ts#L89

I cannot figure out what is happening inside `monero_wallet_keys.js`.

![image](https://github.com/woodser/monero-ts/assets/6230798/510be6bf-9faf-4085-81de-ed8101dfec49)

**Comment by dutu** [comment]
The issue is triggered when evaluating `if` condition in function `InstantiateAsync()` in `monero_wallet_keys.js`:
```js
if (!wasmBinary && typeof WebAssembly.instantiateStreaming == "function" && !isDataURI(wasmBinaryFile) && !isFileURI(wasmBinaryFile) && typeof fetch == "function") {
```

The trigger is the availability of functioin `WebAssembly.instantiateStreaming()`.

Prior node.js 18.1.0 `WebAssembly.instantiateStreaming()` was not available, hence `if` condition resolves to `false`. 
Also for later node.js releases flag `--no-experimental-fetch` can be used, which makes `WebAssembly.instantiateStreaming()` unavailable, hence the fault is not triggered.

So:
* to avoid the error: use node.js flag `--no-experimental-fetch` (or node.js < 18.1.0)
* to reporoduce the error: use node.js > 18.1.0 and without flag `--no-experimental-fetch`


When `WebAssembly.instantiateStreaming()` is not available, the error is not triggered, but also `isDataURI(wasmBinaryFile)` is not evaluated. In case `WebAssembly.instantiateStreaming()`  is available `isDataURI(wasmBinaryFile)` returns `false` since `wasmBinaryFile` is not prefixed with `file://`.



Hope this analysis helps and can lead to a solution.
In the meantime use the flag `--no-experimental-fetch`, which will avoind the issue.

**Comment by woodser** [comment]
I can recreate the error by removing the `--no-experimental-fetch` flag. 👍

So yeah, the workaround to fix this issue for now is to add `--no-experimental-fetch` flag when calling node.
